name: Java/Angular app
on:
  push:
    branches: [ "main" ]
jobs:
  backend-check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'semeru'
        cache: maven
    - name: Set database connection properties
      run: |
        echo "spring.datasource.url=jdbc:h2:mem:testdb" > src/main/resources/application.properties
        echo "spring.datasource.driverClassName=org.h2.Driver" >> src/main/resources/application.properties
        echo "spring.datasource.username=sa" >> src/main/resources/application.properties
        echo "spring.datasource.password=" >> src/main/resources/application.properties
        echo "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect" >> src/main/resources/application.properties
        echo "spring.h2.console.enabled=true" >> src/main/resources/application.properties
        echo "spring.h2.console.path=/h2-console" >> src/main/resources/application.properties
    - name: Run tests
      run: mvn -B test --file pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup database configuration
        run: |
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:spring_app
          context: "{{defaultContext}}:backend"
      - name: Build and push nginx proxy
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:spring_nginx
          context: "{{defaultContext}}:backend/nginx"
  frontend-check-code:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: ./frontend
      steps:
        - name: Check out repository code
          uses: actions/checkout@v5
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            version: '18'
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
        - run: npm install
        - run: npm run build --if-present
        - run: npm run test
  frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:angular_app
          context: "{{defaultContext}}:frontend"
      - name: Build and push nginx proxy
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:angular_nginx
          context: "{{defaultContext}}:frontend/nginx"